CREATE TABLE users (
		id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
		`email` VARCHAR(255) NOT NULL,
		`first` VARCHAR(150) NOT NULL,
		`last` VARCHAR(150) NOT NULL,
		`created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=Innodb;

CREATE TABLE content (
		`name` VARCHAR(200) NOT NULL PRIMARY KEY,
		`type` ENUM('post', 'page'),
		`content` LONGTEXT,
		user_id INT UNSIGNED NOT NULL,
		created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
		modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
		published TIMESTAMP NULL,
		CONSTRAINT `fk-user-content` FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT
) ENGINE=Innodb;

CREATE TABLE tags (
	
) ENGINE=Innodb;

CREATE TABLE revisions (
		content_id VARCHAR(200) NOT NULL,
		revision INT UNSIGNED NOT NULL,
		`content` LONGTEXT,
		`created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
		PRIMARY KEY (content_id, revision),
		CONSTRAINT `fk-post-revisions` FOREIGN KEY (content_id) REFERENCES content(id)
) ENGINE=Innodb;